name: "Tests"

on: [pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Kiev"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install node_modules
        run: npm install

      - name: Run tests
        run: npm run test

  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install node_modules
        run: npm install

      - name: Run ESLint
        run: npm run lint -- --no-fix --max-warnings 0

  stylelint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install node_modules
        run: npm install

      - name: Run Stylelint
        run: npm run lint:scss
